# TODO jen pro testovani, rozpis je treba dodelat

games:
  18:
    # round 1
    1:
      1:
      - 1
      - 2
      2:
      - 3
      - 4
      3:
      - 5
      - 6
      4:
      - 7
      - 8
      5:
      - 9
      - 10
      6:
      - 11
      - 12
      7:
      - 13
      - 14
      8:
      - 15
      - 16
      9:
      - 17
      - 18
     
    # round 2
    2:
      1:
      - 10
      - 1
      2:
      - 11
      - 2
      3:
      - 12
      - 3
      4:
      - 13
      - 4
      5:
      - 14
      - 5
      6:
      - 15
      - 6
      7:
      - 16
      - 7
      8:
      - 17
      - 8
      9:
      - 18
      - 9
      
    # round 1
    3:
      1:
      - 2
      - 1
      2:
      - 4
      - 3
      3:
      - 6
      - 5
      4:
      - 8
      - 7
      5:
      - 10
      - 9
      6:
      - 12
      - 11
      7:
      - 14
      - 13
      8:
      - 16
      - 15
      9:
      - 18
      - 17
     
    # round 4
    4:
      1:
      - 1
      - 10
      2:
      - 2
      - 11
      3:
      - 3
      - 12
      4:
      - 4
      - 13
      5:
      - 5
      - 14
      6:
      - 6
      - 15
      7:
      - 7
      - 16
      8:
      - 8
      - 17
      9:
      - 9
      - 18